import './globals.css';
import React from 'react';
import { ClerkProvider } from '@clerk/nextjs/app-beta';

export const metadata = {
  title: 'Literati',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
